<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MyDesktopApp</RootNamespace>
    <AssemblyName>MyDesktopApp</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyDesktopApp.Core\MyDesktopApp.Core.csproj" />
    <ProjectReference Include="..\MyDesktopApp.Utilities\Mydesktopapp.Utilities.csproJ" />
  </ItemGroup>

</Project>
